package com.zynpath.backend.multiplayer.model;

/**
 * Versioned real-time WebSocket event types for multiplayer matchmaking and match sessions.
 *
 * Implements Prompt 20 Section 30.
 */
public enum MultiplayerEventType {
    MATCHMAKING_STARTED,
    MATCH_FOUND,
    MATCHMAKING_CANCELLED,
    MATCHMAKING_TIMEOUT,

    PLAYER_JOINED,
    PLAYER_LEFT,
    PLAYER_READY,

    MATCH_COUNTDOWN,
    MATCH_STARTED,

    PLAYER_PROGRESS,
    PLAYER_COMPLETED,

    MATCH_COMPLETED,
    MATCH_CANCELLED,
    MATCH_EXPIRED,

    RECONNECT_STATE,
    REACTION_EMITTED,

    // Friend Duel & Invitations (Prompt 22)
    FRIEND_DUEL_INVITED,
    FRIEND_DUEL_ACCEPTED,
    FRIEND_DUEL_DECLINED,
    FRIEND_DUEL_CANCELLED,
    FRIEND_DUEL_EXPIRED,
    FRIEND_DUEL_MATCH_CREATED,

    // Rematch (Prompt 22)
    REMATCH_REQUESTED,
    REMATCH_ACCEPTED,
    REMATCH_DECLINED,
    REMATCH_EXPIRED,

    // Mini League (Prompt 23)
    MINI_LEAGUE_ROOM_CREATED,
    MINI_LEAGUE_INVITED,
    MINI_LEAGUE_PLAYER_JOINED,
    MINI_LEAGUE_PLAYER_LEFT,
    MINI_LEAGUE_HOST_CHANGED,
    MINI_LEAGUE_READY_CHANGED,
    MINI_LEAGUE_MATCH_CREATED,
    MINI_LEAGUE_ROOM_CANCELLED,
    MINI_LEAGUE_ROOM_EXPIRED,
    // Friends Arena (Prompt 18 & 19)
    FRIENDS_ARENA_ROOM_CREATED,
    FRIENDS_ARENA_PLAYER_JOINED,
    FRIENDS_ARENA_PLAYER_LEFT,
    FRIENDS_ARENA_MEMBERSHIP_CHANGED,
    FRIENDS_ARENA_HOST_CHANGED,
    FRIENDS_ARENA_ROOM_CLOSED,
    FRIENDS_ARENA_MATCH_STARTING,
    FRIENDS_ARENA_MATCH_STARTED,
    FRIENDS_ARENA_PLAYER_PROGRESS,
    FRIENDS_ARENA_PLAYER_COMPLETED,
    FRIENDS_ARENA_PLAYER_DISCONNECTED,
    FRIENDS_ARENA_PLAYER_RECONNECTED,
    FRIENDS_ARENA_MATCH_COMPLETED,

    ERROR
}

